- name: Copy app files to VM
  copy:
    src: /home/tanvir_mahfuz/app
    dest: /home/{{ ansible_user }}/server
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  register: copy_result
  ignore_errors: yes

- name: Build Docker image from Dockerfile
  docker_image:
    name: this-image-prints-commit-hash
    tag: latest
    source: build
    build:
      path: /home/{{ ansible_user }}/server/app
  ignore_errors: yes

- name: Run Docker container
  docker_container:
    name: commit-hash-printer
    image: this-image-prints-commit-hash:latest
    state: started
    ports:
      - "3000:3000"
  ignore_errors: yes

- name: Show if copy of the file failed
  debug:
    var: copy_result.failed
