name: Deploy Docker Image

on:
  workflow_run:
    workflows: ["CI - Build & Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vm-ip:
          - ${{ secrets.VM1_IP }}
          - ${{ secrets.VM2_IP }}
          - ${{ secrets.VM3_IP }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VM ${{ matrix.vm-ip }}
        uses: ./actions/deploy
        with:
          vm-ip: ${{ matrix.vm-ip }}
          vm-user: ${{ secrets.VM_USER }}
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
