name: CD - setting starting servers in vms
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vm: [VM1, VM2, VM3]

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to VM ${{ matrix.vm }}
        uses: ./actions/deploy
        env:
          # VM IPs
          VM1_IP: ${{ secrets.VM1_IP }}
          VM2_IP: ${{ secrets.VM2_IP }}
          VM3_IP: ${{ secrets.VM3_IP }}

          # VM Users
          VM1_USER: ${{ secrets.VM1_USER }}
          VM2_USER: ${{ secrets.VM2_USER }}
          VM3_USER: ${{ secrets.VM3_USER }}

          # DockerHub
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        with:
          vm-ip: ${{ env[matrix.vm ~ "_IP"] }}
          vm-user: ${{ env[matrix.vm ~ "_USER"] }}
          dockerhub-username: ${{ env.DOCKERHUB_USERNAME }}
